"""
Generates ProFTPd virtual user files:

  ftpd.passwd       — authentication for all users (regular + trusted)
  ftpd_trusted.conf — <IfUser> blocks that give trusted users their own chroot + R/W access

Format per ftpd.passwd line:
  username:hashed_password:uid:gid:gecos:home_dir:shell

Regular users:  home_dir = /   (chrooted to global FTP root by DefaultRoot in proftpd.conf)
Trusted users:  home_dir = FTP_BASE_PATH/<ftp_home_dir>  (chrooted by <IfUser> block)
"""

import os
import stat
from sqlalchemy.orm import Session
from config import settings
from models import User, TrustedFtpUser


def regenerate_ftpd_passwd(db: Session) -> int:
    """Write ftpd.passwd for all enabled users (regular + trusted). Returns total count written."""
    users   = db.query(User).filter(User.enabled == True).order_by(User.username).all()
    trusted = db.query(TrustedFtpUser).filter(TrustedFtpUser.enabled == True).order_by(TrustedFtpUser.username).all()

    lines = []
    for u in users:
        lines.append(
            f"{u.username}:{u.password_hash}:"
            f"{settings.ftp_uid}:{settings.ftp_gid}:"
            f"FTP User {u.username}:/:/sbin/nologin"
        )
    for u in trusted:
        home = f"{settings.ftp_base_path}/{u.ftp_home_dir}"
        lines.append(
            f"{u.username}:{u.password_hash}:"
            f"{settings.ftp_uid}:{settings.trusted_ftp_gid}:"
            f"Trusted FTP User {u.username}:{home}:/sbin/nologin"
        )

    content = "\n".join(lines) + ("\n" if lines else "")
    _atomic_write(settings.ftpd_passwd_path, content)
    return len(users) + len(trusted)


def regenerate_ftpd_trusted_conf(db: Session) -> int:
    """Write ftpd_trusted.conf with <IfUser> chroot blocks for enabled trusted users."""
    trusted = db.query(TrustedFtpUser).filter(TrustedFtpUser.enabled == True).order_by(TrustedFtpUser.username).all()

    lines = ["# Auto-generated by ciosuseradd — do not edit manually", ""]
    for u in trusted:
        home = f"{settings.ftp_base_path}/{u.ftp_home_dir}"
        lines += [
            f"<IfUser {u.username}>",
            f"  DefaultRoot {home}",
            f"  <Directory {home}>",
            f"    AllowOverwrite on",
            f"    <Limit STOR APPE MKD XMKD DELE RNFR RNTO RMD XRMD>",
            f"      AllowAll",
            f"    </Limit>",
            f"  </Directory>",
            f"</IfUser>",
            "",
        ]

    _atomic_write(settings.ftpd_trusted_conf_path, "\n".join(lines))
    return len(trusted)


def _atomic_write(path: str, content: str) -> None:
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(content)
    os.chmod(tmp, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP)
    os.rename(tmp, path)
